### Create a message to send (Dev environment)
POST {{host}}:8080/emails
Content-Type: application/json; charset=UTF-8

{
  "templateId": 1,
  "recipients": [
    {
      "email": "denis@gorbatih.ru",
      "name": "Denis Gorbatykh"
    }
  ]
}

### Create a message to send (Demo environment)
POST {{host}}:8080/emails
Content-Type: application/json; charset=UTF-8

{
  "templateId": 47,
  "recipients": [
    {
      "email": "vic@tim.org",
      "name": "John Doe"
    }
  ],
  "params": {
    "testSubject": "Joe2"
  }
}